# Site settings
title: "Shadi Barhoumi"
description: "Shadi Barhoumi's resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shadi Barhoumi"
resume_title:                   "Full Stack Javascript Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "bshadi@stanford.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(650) 255-7536"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "bshadi@stanford.edu"
display_header_contact_info:    "true"

resume_header_intro: "People-oriented. Deep thinker. Pragmatic developer."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/shadibarhoumi/"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/shadi-barhoumi-21037447/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
